sonar.projectKey=sonar-node-app
	sonar.projectName=Sonar Node App
	sonar.projectVersion=1.0
	sonar.sources=.
	sonar.host.url=http://localhost:9000
	sonar.login=squ_cdf5def2dda6109a4aba12f1d3f1134f6a63011e
